complementary_filter_gain_node:
  ros__parameters:
    gain_acc: 0.001
    gain_mag: 0.0
    bias_alpha: 0.001
    do_bias_estimation: true
    do_adaptive_gain: false
    use_mag: false
    fixed_frame: "odom"
    publish_tf: false
    reverse_tf: false
    constant_dt: 0.0
    publish_debug_topics: false

    qos_overrides:
      /imu/data:
        subscription:
          depth: 10
          durability: volatile
          history: keep_last
          reliability: best_effort

      /imu/mag:
        subscription:
          depth: 10
          durability: volatile
          history: keep_last
          reliability: reliable
